<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Javier Kniffki" />
<meta name="author" content="javierkniffki@gmail.com" />

<meta name="date" content="2021-12-16" />

<title>Regresión lineal 1</title>

<script src="site_libs/header-attrs-2.11/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Curso R CCPP 2021</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="intro_basica.html">Primera sesión</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Segunda sesion
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="borrar.html">Segunda sesión</a>
    </li>
    <li>
      <a href="regresion_1.html">Ejercicios segunda sesión</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Regresión lineal 1</h1>
<h3 class="subtitle">Introducción a R. Ciencias Políticas</h3>
<h4 class="author">Javier Kniffki</h4>
<h4 class="author"><a href="mailto:javierkniffki@gmail.com" class="email">javierkniffki@gmail.com</a></h4>
<h4 class="date">2021-12-16</h4>

</div>


<script>
function myFunction() {
    var x = document.getElementById("myDIV");
    if (x.style.display === "none") {
        x.style.display = "block";
    } else {
        x.style.display = "none";
    }
}
</script>
<div id="lectura-de-los-datos" class="section level1">
<h1>Lectura de los datos</h1>
<p>En esta ocasión vamos a leer los datos depositados en el repositorio de github para agilizar el proceso. Pero muchas veces trabajaremos con datos a nivel local para leer estos conviene recordar unas cuantas funciones y algunas nociones para trabjar con archivos en R</p>
<div id="repaso-gestión-de-archivos-en-r" class="section level2">
<h2>Repaso gestión de archivos en R</h2>
<p>Para verificar el entorno de trabajo es decir la carpeta donde R esta ahora mismo empleamos <code>getwd()</code> para cambiar dicho entorno podemos emplear la función <code>setwd()</code>.</p>
<pre class="r"><code># Cambiando el directorio de trabajo a Rproject la carpeta de data
setwd(&quot;C:/Users/UserName/Documents/Rproject/data&quot;)</code></pre>
<p>Recuerda que en R <strong>“\”</strong> es un scape character que sirve para identificar otras cadenas de texto asi que es necesario poner <strong>“\\”</strong> en la especificación de la dirección o emplear directamente <strong>“/”</strong>.</p>
<div class="alert alert-success">
<p>Correcto: <br> “C:/Users/UserName/Documents/Rproject/data” <br> “C:\\Users\\UserName\\Documents\\Rproject\\data”</p>
</div>
<div class="alert alert-danger">
<p>Incorrecto:<br> “C:\Users\UserName\Documents\Rproject\data”</p>
</div>
<p>Para listar los archivos de una carpeta empleamos la función <code>ls("directorio/donde/listar/archivos")</code> el resultado lo podemos guardad en un vector y acceder a el de la forma habitual. Otra función interesante es <code>file.choose()</code> la cual abrira un navegador de archivos y nos permitira seleccionar un archivo o carpeta concreta de forma manual imprimiendo su path en la consola. Recuerda que tambien podemos guardar este valor en un objeto <code>archivo &lt;- file.choose()</code></p>
<div class="alert alert-warning">
<p>Si estamos trabajando en un proyecto el working directory sera el del proyecto.</p>
</div>
</div>
<div id="lectura" class="section level2">
<h2>Lectura</h2>
<p>A continuación pasamos a leer los datos. En este caso se trata de un <code>.csv</code> <strong>Comma separeted values</strong></p>
<pre class="r"><code># para leer en local
file.exists(&quot;C:/Users/javro/Documents/probando2/datos/CD_hdi_corr_sc.csv&quot;)</code></pre>
<pre><code>## [1] TRUE</code></pre>
<pre class="r"><code># función de R base
datos &lt;- read.csv(&quot;C:/Users/javro/Documents/probando2/datos/CD_hdi_corr_sc.csv&quot;)</code></pre>
</div>
</div>
<div id="exploración-inical" class="section level1">
<h1>Exploración inical</h1>
<p>Exploramos de forma habitual</p>
<pre class="r"><code>str(datos)</code></pre>
<pre><code>## &#39;data.frame&#39;:    7488 obs. of  8 variables:
##  $ Entity                     : chr  &quot;Afghanistan&quot; &quot;Afghanistan&quot; &quot;Afghanistan&quot; &quot;Afghanistan&quot; ...
##  $ Code                       : chr  &quot;AFG&quot; &quot;AFG&quot; &quot;AFG&quot; &quot;AFG&quot; ...
##  $ Continent                  : chr  &quot;Asia&quot; &quot;Asia&quot; &quot;Asia&quot; &quot;Asia&quot; ...
##  $ Year                       : int  1990 1991 1992 1993 1994 1995 1996 1997 1998 1999 ...
##  $ avg_years_school           : num  1.49 1.6 1.6 1.7 1.8 1.9 1.9 2 2 2.1 ...
##  $ Corruption_perception_index: int  NA NA NA NA NA NA NA NA NA NA ...
##  $ PopEstimate                : int  12412311 13299016 14485543 15816601 17075728 18110662 18853444 19357126 19737770 20170847 ...
##  $ Human_Dev_index            : num  NA NA NA NA NA NA NA NA NA NA ...</code></pre>
<pre class="r"><code>summary(datos)</code></pre>
<pre><code>##     Entity              Code            Continent              Year      avg_years_school Corruption_perception_index
##  Length:7488        Length:7488        Length:7488        Min.   :1990   Min.   : 0.290   Min.   : 8.00              
##  Class :character   Class :character   Class :character   1st Qu.:1998   1st Qu.: 4.800   1st Qu.:28.25              
##  Mode  :character   Mode  :character   Mode  :character   Median :2006   Median : 7.800   Median :38.00              
##                                                           Mean   :2006   Mean   : 7.429   Mean   :42.99              
##                                                           3rd Qu.:2013   3rd Qu.:10.100   3rd Qu.:56.00              
##                                                           Max.   :2021   Max.   :14.100   Max.   :92.00              
##                                                                          NA&#39;s   :2669     NA&#39;s   :6266               
##   PopEstimate        Human_Dev_index 
##  Min.   :7.620e+02   Min.   :0.1990  
##  1st Qu.:3.635e+05   1st Qu.:0.5290  
##  Median :4.557e+06   Median :0.6800  
##  Mean   :2.819e+07   Mean   :0.6551  
##  3rd Qu.:1.692e+07   3rd Qu.:0.7830  
##  Max.   :1.444e+09   Max.   :0.9530  
##                      NA&#39;s   :2731</code></pre>
<pre class="r"><code>hist(datos$avg_years_school)</code></pre>
<p><img src="regresion_1_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<pre class="r"><code>hist(datos$Corruption_perception_index)</code></pre>
<p><img src="regresion_1_files/figure-html/unnamed-chunk-5-2.png" width="672" /></p>
<pre class="r"><code>mean(datos$Corruption_perception_index)</code></pre>
<pre><code>## [1] NA</code></pre>
<pre class="r"><code>mean(datos$Corruption_perception_index, na.rm = T)</code></pre>
<pre><code>## [1] 42.98936</code></pre>
</div>
<div id="transformaciones" class="section level1">
<h1>Transformaciones</h1>
<p>Normalmente aprobecaharíamos los datos de panel para el ajuste de modelos más fidedignos aqui vamos a sacar una media del rango temporal disponible y revertir el índice de corrupción para hacerlo más sencillo a la hora de interpretar.</p>
<pre class="r"><code>library(dplyr)

# función propia que no tiene en cuenta los NA
mimedia &lt;- function(x) { mean(x, na.rm = T)}

# Seleción de variables, agrupación y calculo 
 datos_mod &lt;- datos |&gt; select(Entity,avg_years_school,Corruption_perception_index,PopEstimate) |&gt; group_by(Entity) |&gt; summarise_all(mimedia)
 
# quitamos casos que no esten completos
datos_mod &lt;- datos_mod[complete.cases(datos_mod),] 
 
 
 # recuperamos los continentes
 datos_mod2 &lt;- datos_mod |&gt; left_join(unique(datos[,c(&quot;Entity&quot;,&quot;Continent&quot;)]))  
 
 
 # cambiar la variable corruption index 
 datos_mod2 &lt;- datos_mod2 |&gt; mutate(Corruption_perception_index = 100 - Corruption_perception_index)

 
 head(datos_mod2)</code></pre>
<pre><code>## # A tibble: 6 x 5
##   Entity      avg_years_school Corruption_perception_index PopEstimate Continent    
##   &lt;chr&gt;                  &lt;dbl&gt;                       &lt;dbl&gt;       &lt;dbl&gt; &lt;chr&gt;        
## 1 Afghanistan             2.57                        87.9   26068568. Asia         
## 2 Albania                 8.88                        64.9    3038523. Europe       
## 3 Algeria                 6.21                        65.1   34264125. Africa       
## 4 Angola                  4.65                        80.7   20994920. Africa       
## 5 Argentina               9.04                        64.3   39124059. South America
## 6 Armenia                10.9                         65      3055799. Asia</code></pre>
</div>
<div id="modelos" class="section level1">
<h1>Modelos</h1>
<p>El modelo lineal básico ..</p>
<p><span class="math display">\[ Y_{i}=\beta _{0}+\beta _{1}X_{i1}+\beta _{2}X_{i2}+\ldots +\beta _{p}X_{ip}+\epsilon_{i}\]</span></p>
<pre class="r"><code>mod1 &lt;- lm(formula = Corruption_perception_index ~ avg_years_school ,data = datos_mod2)

summary(mod1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Corruption_perception_index ~ avg_years_school, 
##     data = datos_mod2)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -40.673  -9.717   1.710  10.041  36.533 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       86.0829     2.8433   30.28   &lt;2e-16 ***
## avg_years_school  -4.0586     0.3627  -11.19   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 14.8 on 176 degrees of freedom
## Multiple R-squared:  0.4157, Adjusted R-squared:  0.4123 
## F-statistic: 125.2 on 1 and 176 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>confint(mod1)</code></pre>
<pre><code>##                     2.5 %    97.5 %
## (Intercept)      80.47163 91.694189
## avg_years_school -4.77452 -3.342769</code></pre>
<p>Nuestro modelo entonces sería:</p>
<p><span class="math display">\[Corruption\_perception \ =\ 86.0829 + -4.0586*avg\_years\_shcool+\epsilon \]</span></p>
<pre class="r"><code>library(ggplot2)

ggplot(data = datos_mod2,aes(x = avg_years_school, y = Corruption_perception_index)) +
  geom_point() +
  geom_smooth(method = &quot;lm&quot;)</code></pre>
<p><img src="regresion_1_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<pre class="r"><code>mod2 &lt;- lm(formula = Corruption_perception_index ~ poly(avg_years_school,2) ,data = datos_mod2)

summary(mod2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Corruption_perception_index ~ poly(avg_years_school, 
##     2), data = datos_mod2)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -36.467  -9.603   1.062   9.017  37.326 
## 
## Coefficients:
##                            Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                   56.79       1.08  52.600  &lt; 2e-16 ***
## poly(avg_years_school, 2)1  -165.65      14.40 -11.499  &lt; 2e-16 ***
## poly(avg_years_school, 2)2   -47.57      14.40  -3.302  0.00116 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 14.4 on 175 degrees of freedom
## Multiple R-squared:  0.4499, Adjusted R-squared:  0.4436 
## F-statistic: 71.57 on 2 and 175 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>confint(mod2)</code></pre>
<pre><code>##                                 2.5 %     97.5 %
## (Intercept)                  54.66181   58.92363
## poly(avg_years_school, 2)1 -194.07878 -137.21904
## poly(avg_years_school, 2)2  -75.99581  -19.13607</code></pre>
<pre class="r"><code>ggplot(data = datos_mod2,aes(x = avg_years_school, y = Corruption_perception_index)) +
  geom_point() +
  geom_smooth(method = &quot;lm&quot;,formula = y ~ poly(x,2))</code></pre>
<p><img src="regresion_1_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>El segundo modelo quedaría asi:</p>
<p><span class="math display">\[Corruption\_perception \ =\ 56.79  -165.65*avg\_years\_shcool  -47.57 * avg\_years\_school^2+ \epsilon \]</span></p>
</div>
<div id="diagnóstico" class="section level1">
<h1>Diagnóstico</h1>
<p>Para evaluar un modelo lineal es importantante tener en cuenta estas 4 condiciones:</p>
<ul>
<li>Linealidad</li>
<li>Homocedasticidad ( <span class="math inline">\(Var(e_i) = \sigma^2\)</span> con <span class="math inline">\(\sigma^2\)</span> constante )</li>
<li>Normalidad: ( <span class="math inline">\(\epsilon_i \sim N(0,\sigma^2)\)</span> )</li>
<li>Independencia de los errores</li>
</ul>
<pre class="r"><code>plot(mod1, col = &quot;blue&quot;)</code></pre>
<p><img src="regresion_1_files/figure-html/unnamed-chunk-11-1.png" width="672" /><img src="regresion_1_files/figure-html/unnamed-chunk-11-2.png" width="672" /><img src="regresion_1_files/figure-html/unnamed-chunk-11-3.png" width="672" /><img src="regresion_1_files/figure-html/unnamed-chunk-11-4.png" width="672" /></p>
<pre class="r"><code>plot(mod2, col = &quot;green&quot;)</code></pre>
<p><img src="regresion_1_files/figure-html/unnamed-chunk-11-5.png" width="672" /><img src="regresion_1_files/figure-html/unnamed-chunk-11-6.png" width="672" /><img src="regresion_1_files/figure-html/unnamed-chunk-11-7.png" width="672" /><img src="regresion_1_files/figure-html/unnamed-chunk-11-8.png" width="672" /></p>
</div>
<div id="comunicando-resultados" class="section level1">
<h1>Comunicando Resultados</h1>
<div id="tablas-comparativas" class="section level2">
<h2>Tablas comparativas</h2>
<pre class="r"><code>library(report)
library(stargazer)

# hacemos otro modelo para incluirlo en la tabla

mod3 &lt;- lm(formula = Corruption_perception_index ~ avg_years_school + log(PopEstimate) ,data = datos_mod2)

stargazer(mod1,mod2,mod3,type = &quot;text&quot;)</code></pre>
<table style="text-align:center">
<tr>
<td colspan="4" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="3">
<em>Dependent variable:</em>
</td>
</tr>
<tr>
<td>
</td>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="3">
Corruption_perception_index
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(1)
</td>
<td>
(2)
</td>
<td>
(3)
</td>
</tr>
<tr>
<td colspan="4" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
avg_years_school
</td>
<td>
-4.059<sup>***</sup>
</td>
<td>
</td>
<td>
-4.056<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.363)
</td>
<td>
</td>
<td>
(0.364)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
poly(avg_years_school, 2)1
</td>
<td>
</td>
<td>
-165.649<sup>***</sup>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
(14.405)
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
poly(avg_years_school, 2)2
</td>
<td>
</td>
<td>
-47.566<sup>***</sup>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
(14.405)
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
PopEstimate
</td>
<td>
</td>
<td>
</td>
<td>
0.000
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
(0.000)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Constant
</td>
<td>
86.083<sup>***</sup>
</td>
<td>
56.793<sup>***</sup>
</td>
<td>
86.007<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(2.843)
</td>
<td>
(1.080)
</td>
<td>
(2.880)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td colspan="4" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Observations
</td>
<td>
178
</td>
<td>
178
</td>
<td>
178
</td>
</tr>
<tr>
<td style="text-align:left">
R<sup>2</sup>
</td>
<td>
0.416
</td>
<td>
0.450
</td>
<td>
0.416
</td>
</tr>
<tr>
<td style="text-align:left">
Adjusted R<sup>2</sup>
</td>
<td>
0.412
</td>
<td>
0.444
</td>
<td>
0.409
</td>
</tr>
<tr>
<td style="text-align:left">
Residual Std. Error
</td>
<td>
14.805 (df = 176)
</td>
<td>
14.405 (df = 175)
</td>
<td>
14.846 (df = 175)
</td>
</tr>
<tr>
<td style="text-align:left">
F Statistic
</td>
<td>
125.192<sup>***</sup> (df = 1; 176)
</td>
<td>
71.570<sup>***</sup> (df = 2; 175)
</td>
<td>
62.270<sup>***</sup> (df = 2; 175)
</td>
</tr>
<tr>
<td colspan="4" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
<em>Note:</em>
</td>
<td colspan="3" style="text-align:right">
<sup><em></sup>p&lt;0.1; <sup><strong></sup>p&lt;0.05; <sup></strong></em></sup>p&lt;0.01
</td>
</tr>
</table>
</div>
<div id="texto" class="section level2">
<h2>Texto</h2>
<pre class="r"><code>library(report)
report(mod2)</code></pre>
<pre><code>## We fitted a linear model (estimated using OLS) to predict Corruption_perception_index with avg_years_school (formula: Corruption_perception_index ~ poly(avg_years_school, 2)). The model explains a statistically significant and substantial proportion of variance (R2 = 0.45, F(2, 175) = 71.57, p &lt; .001, adj. R2 = 0.44). The model&#39;s intercept, corresponding to avg_years_school = 0, is at 56.79 (95% CI [54.66, 58.92], t(175) = 52.60, p &lt; .001). Within this model:
## 
##   - The effect of avg years school [1st degree] is statistically significant and negative (beta = -165.65, 95% CI [-194.08, -137.22], t(175) = -11.50, p &lt; .001; Std. beta = -8.58, 95% CI [-10.05, -7.11])
##   - The effect of avg years school [2nd degree] is statistically significant and negative (beta = -47.57, 95% CI [-76.00, -19.14], t(175) = -3.30, p = 0.001; Std. beta = -2.46, 95% CI [-3.94, -0.99])
## 
## Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using the Wald approximation.</code></pre>
</div>
<div id="gráfico" class="section level2">
<h2>Gráfico</h2>
<pre class="r"><code>p1 &lt;- ggplot(data = datos_mod2,aes(x = avg_years_school, y = Corruption_perception_index)) +
  geom_smooth(method = &quot;lm&quot;,formula = y ~ poly(x,2)) 

p1  </code></pre>
<p><img src="regresion_1_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<pre class="r"><code>p1 + geom_point(color = &quot;blue&quot;)</code></pre>
<p><img src="regresion_1_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<pre class="r"><code>p1 + geom_point(aes(color = Continent))</code></pre>
<p><img src="regresion_1_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<pre class="r"><code>p1 + geom_point(aes(color = Continent,size = PopEstimate),alpha = 0.8)</code></pre>
<p><img src="regresion_1_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<pre class="r"><code>p2 &lt;- ggplot(data = datos_mod2,aes(x = avg_years_school, y = Corruption_perception_index)) +
  geom_point(aes(color = Continent,size = PopEstimate),alpha = 0.8) +
  geom_smooth(method = &quot;lm&quot;,formula = y ~ poly(x,2),color = &quot;#7FFFD4&quot;) 

p2  </code></pre>
<p><img src="regresion_1_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<pre class="r"><code>p2 &lt;- p2 + theme_minimal()
p2</code></pre>
<p><img src="regresion_1_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<pre class="r"><code>p2 &lt;- p2 + guides(size = &quot;none&quot;) + theme(legend.position = &quot;bottom&quot;)
p2</code></pre>
<p><img src="regresion_1_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<pre class="r"><code>p2 &lt;- p2 + scale_size(range = c(2,10)) 
p2</code></pre>
<p><img src="regresion_1_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<pre class="r"><code>p2 &lt;- p2 + scale_color_manual(values = c(&quot;#b22222&quot;,&quot;forestgreen&quot;,&quot;dodgerblue3&quot;,&quot;gold&quot;,&quot;purple&quot;,&quot;orange3&quot;))
p2</code></pre>
<p><img src="regresion_1_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<pre class="r"><code>p2 &lt;- p2 + labs(title = &quot;Corruption and Education&quot;,
           subtitle = &quot;Evidence from longitudinal data of 178 countries&quot;,
           caption = &quot;data source: Our Worl in data, average from 1990-2021&quot;,
           x = &quot;Average years of schooling in current adults&quot;,y = &quot;Corruption perception index&quot;)
p2</code></pre>
<p><img src="regresion_1_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
</div>
</div>
<div id="section" class="section level1">
<h1></h1>
</div>
<div id="ejercicios" class="section level1 tabset tabset-fade">
<h1 class="tabset tabset-fade">Ejercicios</h1>
<ol style="list-style-type: decimal">
<li>Empleando el objeto <strong>datos</strong> extrae los valores de Francia ¿cuantos valores perdidos hay en la variable referida a la percepción de la corrupción?</li>
</ol>
<details>
<summary class="btn btn-primary">
Ver la respuesta
</summary>
<pre class="r"><code>fr &lt;- datos[datos$Code == &quot;FRA&quot;,]
head(fr)</code></pre>
<pre><code>##      Entity Code Continent Year avg_years_school Corruption_perception_index PopEstimate Human_Dev_index
## 2305 France  FRA    Europe 1990             7.33                          NA    56666861           0.779
## 2306 France  FRA    Europe 1991             7.50                          NA    56913580           0.788
## 2307 France  FRA    Europe 1992             7.80                          NA    57147213           0.798
## 2308 France  FRA    Europe 1993             8.10                          NA    57370375           0.804
## 2309 France  FRA    Europe 1994             8.40                          NA    57587122           0.818
## 2310 France  FRA    Europe 1995             8.80                          NA    57801887           0.825</code></pre>
<pre class="r"><code>sum(is.na(fr$Corruption_perception_index))</code></pre>
<pre><code>## [1] 25</code></pre>
</details>
<p><br></p>
<ol start="2" style="list-style-type: decimal">
<li>Construye un modelo con la variable <strong>Human_Dev_index</strong> como variable independiente y <strong>Corruption_perception_index</strong> como dependiente. Emplea la media para cada pais en el rango de años de los datos iniciales ¿Su ajuste (<span class="math inline">\(R^2\)</span>) es mejor que el del objeto mod1 ?</li>
</ol>
<details>
<summary class="btn btn-primary">
Ver la respuesta
</summary>
<pre class="r"><code># función propia que no tiene en cuenta los NA
mimedia &lt;- function(x) { mean(x, na.rm = T)}

# Seleción de variables, agrupación y calculo 
 datos_ej2 &lt;- datos |&gt; select(Entity,Human_Dev_index,Corruption_perception_index) |&gt; group_by(Entity) |&gt; summarise_all(mimedia)
 
# quitamos casos que no esten completos
datos_ej2 &lt;- datos_ej2[complete.cases(datos_ej2),] 

# cambiar la variable corruption index 
datos_ej2 &lt;- datos_ej2 |&gt; mutate(Corruption_perception_index = 100 - Corruption_perception_index)

# ajustamos el modelo
mod_ej2 &lt;- lm(data = datos_ej2,Corruption_perception_index~Human_Dev_index)


# R cuadrado
summary(mod_ej2)$r.squared </code></pre>
<pre><code>## [1] 0.5350781</code></pre>
<pre class="r"><code>summary(mod_ej2)$r.squared &gt; summary(mod1)$r.squared</code></pre>
<pre><code>## [1] TRUE</code></pre>
</details>
<p><br></p>
<ol start="3" style="list-style-type: decimal">
<li>Obten el gráfico de dispersión con la recta de la regresión para el modelo del ejercicio 2</li>
</ol>
<details>
<summary class="btn btn-primary">
Ver la respuesta
</summary>
<pre class="r"><code>ggplot(data = datos_ej2,aes(x = Human_Dev_index, y = Corruption_perception_index)) +
  geom_point() +
  geom_smooth(method = &quot;lm&quot;)</code></pre>
<p><img src="regresion_1_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
</details>
<p><br></p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
